[package]
name = "bigfile-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
bigfile = { path = "../bigfile" }
eframe = "0.33.0"
egui_extras = { version = "0.33.0", features = ["all_loaders"] }
rfd = "0.15.4"
